##### $ZSH_HOME will be generated by GNU make

for ASSET in "local_configs" "configs";
  do
    CONFIG_DIR="${ZSH_HOME}/${ASSET}"
    if [ -d $CONFIG_DIR ] && [ -r $CONFIG_DIR ] && [ -x $CONFIG_DIR ]; then
      for CONF in $CONFIG_DIR/*;
      do
        [[ ${CONF##*/} = *.zsh ]] && . $CONF
      done
    fi
  done

